name: Build, Test and Publish JavaScript SDK

on:
  push:
    branches:
      - main
    paths:
      - 'skrape-js/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: skrape-js
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Check version change
        id: check
        run: |
          git diff HEAD^ HEAD -G"\"version\": \"[^\"]*\"" package.json | grep "\"version\":" || echo "No version change"
          if git diff HEAD^ HEAD -G"\"version\": \"[^\"]*\"" package.json | grep -q "\"version\":"; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            VERSION=$(node -p "require('./package.json').version")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup npm auth
        if: steps.check.outputs.version_changed == 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        if: steps.check.outputs.version_changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.check.outputs.version_changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: js-v${{ steps.check.outputs.version }}
          name: JavaScript SDK v${{ steps.check.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
