name: Build, Test and Publish Python SDK

on:
  push:
    branches:
      - main
    paths:
      - 'skrape-py/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: skrape-py
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: pytest

      - name: Check version change
        id: check
        run: |
          if git diff HEAD^ HEAD setup.py | grep -q "version="; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            VERSION=$(python setup.py --version)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build package
        if: steps.check.outputs.version_changed == 'true'
        run: python -m build

      - name: Publish to PyPI
        if: steps.check.outputs.version_changed == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: skrape-py/dist/

      - name: Create GitHub Release
        if: steps.check.outputs.version_changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: py-v${{ steps.check.outputs.version }}
          name: Python SDK v${{ steps.check.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
